name: Get all the ENVs for diff OS
on:
    workflow_dispatch: 
jobs:
    env_on_windows:
        runs-on: windows-latest
        steps:
            - run: env

    env_on_ubuntu:
        needs: [env_on_windows]
        runs-on: ubuntu-latest
        steps:
            - run: env 
            - run: echo "the Github_Actor is ${{env.GITHUB_ACTOR}}"

    env_on_mac:
        needs: [env_on_windows,env_on_ubuntu]
        runs-on: macos-latest
        steps: 
            - run: env 

    env_on_macs:
        needs: [env_on_windows]
        runs-on: windows-latest
        steps: 
            - run: env 

