name: first github actions 

on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: windows-latest
        
        steps:
        - name: checkout action
          uses: actions/checkout@v3
        
        - name: setup Node.Js
          uses: actions/setup-node@v3
          with: 
            node-version: '20'
        # - name: run main.js 
        #   run : node main.js 
    test:
        needs: [build]
        runs-on: windows-latest
        steps:
        - name: run a script
          uses: |
            Write-Host "I love Jesus"
            Write-Host "And I understand everything that i engage into"    
            
    stage:
        runs-on: windows-latest
        steps:
        - name: run a script
          run: |
            Write-Host "I love Jesus"
            Write-Host "And I understand everything that i engage into"
    