name: testing for worflow
on:
    push:
        branches: [main]
    workflow_dispatch: 

jobs:
  job1:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: creating a file
        run: |
          Add-Content -Path ./mytest.zip -Value "I love to do this test"
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: my-artifact
          path: ./mytests.zip
          if-no-files-found: error
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"