name: Experiment variables btw steps
on:
    push:
        branches: ["main"]
    workflow_dispatch: 
jobs:
    Variables:
        runs-on: windows-latest
        steps:
            - name: make custom env variable
              run: |
                Write-Host "creating an environment variable"
                Add-content -Path $env:GITHUB_ENV -Value "test_var=I love Jesus"
            - name: create a variable
              id: key1
              run: |
                Write-Host "::set-output name=made_var::I love Jesus Again"
            - name: Ref variable in subq steps
              run: |
                Write-Host "First step created var: $env:test_var"
                Write-Host "made_var: ${{steps.key1.outputs.made_var}}"
            - name: Let us do a new thing 
              id: newTest
              run: |
                $output= "id_1=1"
                Add-Content -Path $env:GITHUB_ENV -Value $output
            - name: Get new id_i
              run: |
                 Write-Host "Find out if it worked"
                 $I="${{steps.newTest.outputs.id_1}}"
                 Write-Host  $I
                 Write-Host "Did it work?"
            - name: Let us do a new thing 
              id: newTesting
              run: |
                   $output= "id_1=1"
                   Add-Content -Path $env:GITHUB_ENV -Value $output
              shell: pwsh
               
            - name: Geting new id_1
              run: |
                   Write-Host "Find out if it worked"
                   $I=$env:id_1
                   Write-Host  "The value of id_1 is: $I"
                   Write-Host "Did it work?"
              shell: pwsh           