name: Experiment variables btw steps
on:
    push:
        branches: ["main"]
    workflow_dispatch: 
jobs:
    Variables:
        runs-on: windows-latest
        outputs:
            output1: ${{steps.newTest.outputs.id_1}}
            output2: ${{steps.revision.outputs.output}}
        steps:
            - name: make custom env variable
              run: |
                Write-Host "creating an environment variable"
                Add-content -Path $env:GITHUB_ENV -Value "test_var=I love Jesus"
            - name: Let us do a new thing 
              id: newTest
              run: |
                $output= "id_1=1"
                Add-Content -Path $env:GITHUB_OUTPUT -Value $output
            - name: Let us do a new thing 
              id: revision
              run: |
                  $output= "id_1=19"
                  Add-Content -Path $env:GITHUB_OUTPUT -Value $output
            
            - name: Get new id_i
              run: |
                 Write-Host "Find out if it worked"
                 $I="${{steps.newTest.outputs.id_1}}"
                 Write-Host " this is the value of I: $I"
                 Write-Host "Did it work?"
    var_next:
        needs: [Variables]
        runs-on: windows-latest
        steps:
            - name: Get variable
              run: |
                 $M= "${{needs.Variables.outputs.output1}}"
                 Write-Host "the value of M is $M"
    var_next2:
        needs: [Variables,var_next]
        runs-on: windows-latest
        steps:
            - name: Get the other output
              run: |
                Write-Host "recent variable: ${{needs.Variables.outputs.output2}}"
                
         